trigger:
  branches:
    include: ["master", "bionic"]
  paths:
    exclude: ["**/*.md"]
resources:
- repo: self
  clean: true
queue:
  name: Hosted Ubuntu 1604
steps:
- task: Docker@1
  displayName: Build an image
  inputs:
    arguments: '-t andrewarnott/linux-buildagent:bionic'
    imageName: linux-buildagent:$(Build.BuildId)
    qualifyImageName: false

- task: Docker@1
  displayName: Push image to Docker Hub with bionic tag
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    command: 'Push an image'
    imageName: andrewarnott/linux-buildagent:bionic
    qualifyImageName: false
  condition: succeededOrFailed()
