trigger:
  branches:
    include: ["master", "dotnet-bionic"]
  paths:
    exclude: ["**/*.md"]
resources:
- repo: self
  clean: true
queue:
  name: Hosted Ubuntu 1604
steps:
- task: Docker@1
  displayName: Build an image
  inputs:
    imageName: andrewarnott/dotnet:2.1-sdk-bionic
    qualifyImageName: false

- task: Docker@1
  displayName: Push image to Docker Hub
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    command: 'Push an image'
    imageName: andrewarnott/dotnet:2.1-sdk-bionic
    qualifyImageName: false
  condition: succeededOrFailed()
