trigger:
  branches:
    include: ["master", "devops"]
  paths:
    exclude: ["**/*.md"]
resources:
- repo: self
  clean: true
queue:
  name: Hosted Ubuntu 1604
steps:
- task: Docker@1
  displayName: Build an image
  inputs:
    arguments: '-t andrewarnott/linux-buildagent:$(Build.BuildId) -t andrewarnott/linux-buildagent:latest -t andrewarnott.azurecr.io/linux-buildagent:latest -t andrewarnott.azurecr.io/linux-buildagent:$(Build.BuildId)'
    imageName: linux-buildagent:$(Build.BuildId)
    qualifyImageName: false
    includeSourceTags: true
    includeLatestTag: true

- task: Docker@1
  displayName: Push image to Azure Container Registry
  inputs:
    azureSubscriptionEndpoint: Azure Free Trial (c5eda4ed-4681-4034-8835-65d67e7d4b7c)
    azureContainerRegistry: andrewarnott.azurecr.io
    command: Push an image
    imageName: andrewarnott.azurecr.io/linux-buildagent:$(Build.BuildId)
    qualifyImageName: false
    includeSourceTags: true
    includeLatestTag: true

- task: Docker@1
  displayName: Push image to Docker Hub
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    command: 'Push an image'
    imageName: andrewarnott/linux-buildagent:$(Build.BuildId)
    qualifyImageName: false
    includeLatestTag: true
  condition: succeededOrFailed()
